// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15/10/2024, 12.55.32
const configMerger = require("C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/plugins/**/*.{js,ts,mjs}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/composables/**/*.{js,ts,mjs}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/utils/**/*.{js,ts,mjs}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/OneDrive/Desktop/AYO PKL BISA/Magesty - Copy (2)/app.config.{js,ts,mjs}"] }));

module.exports = config
